hydra:
  sweep:
    subdir: ${hydra.job.override_dirname}

experiment:
  name: MILT Reaseach

# data
dataset_name: 1d_text_blocks
data_dir: data/worlds/shmar_-100_-49_16_90_92_137_LNRJWBQ9CE.npy
batch_size: 128
val_split: 0.1
max_seq_len: 128

# transforms
min_crop_len: 20
max_crop_len: 50

# model
model_name: 
save_every_n_epochs: 2
# model-specific parameters

# optimization
lr_scheduler_name: no_scheduler # no_scheduler, cosine
optimizer_name: adam # adam, sdg
lr: 1e-3
momentum: 0.9
weight_decay: 1e-6
warmup_start_lr: 1e-4
max_epochs: 400

# logging
log_every_n_steps: 10

# device
seed: 1

