hydra:
  sweep:
    subdir: ${hydra.job.override_dirname}

experiment:
  name: MILT Reaseach
  do_pretraining: True
  do_generation: True

# data
dataset_name: minecraft_1d
data_dir: data/worlds/shmar_-98_-52_15_92_94_135_QUKXKV4N6P.npy
batch_size: 128
val_split: 0.1
max_seq_len: 128

# transforms
min_crop_len: 20
max_crop_len: 50

# model
model_name: 
save_every_n_epochs: 2
# model-specific parameters

# optimization
lr_scheduler_name: no_scheduler # no_scheduler, cosine
optimizer_name: adam # adam, sdg
lr: 1e-3
momentum: 0.9
weight_decay: 1e-6
warmup_start_lr: 1e-4
max_epochs: 1

# logging
log_every_n_steps: 10

# transform
transform_name: training

# generation
generation:
  pretrained_model_path:
  transform_name: generation
  generator_name: "minecraft_1d"
  num_generations: 4
  # num_blocks_per_generation: 100

# device
device:
  seed: 1

